import { InstagramIcon, TwitterIcon, LinkedinIcon, YoutubeIcon } from "@/components/icons/SocialIcons";
import { Platform, ContentType, Tone, Language } from "@/types";

// Platform configuration
export const PLATFORMS: {
  id: Platform;
  name: string;
  icon: React.ComponentType<{ className?: string; style?: React.CSSProperties }>;
  color: string;
  bgColor: string;
  contentTypes: { id: ContentType; label: string; charLimit?: number }[];
}[] = [
  {
    id: "instagram",
    name: "Instagram",
    icon: InstagramIcon,
    color: "#E1306C",
    bgColor: "rgba(225, 48, 108, 0.1)",
    contentTypes: [
      { id: "caption", label: "Caption", charLimit: 2200 },
      { id: "reel-hook", label: "Reel Hook", charLimit: 150 },
      { id: "bio", label: "Bio", charLimit: 150 },
      { id: "hashtag-set", label: "Hashtag Set", charLimit: 2200 },
    ],
  },
  {
    id: "twitter",
    name: "Twitter / X",
    icon: TwitterIcon,
    color: "#1DA1F2",
    bgColor: "rgba(29, 161, 242, 0.1)",
    contentTypes: [
      { id: "tweet", label: "Tweet", charLimit: 280 },
      { id: "thread", label: "Thread (5 tweets)" },
      { id: "reply-hook", label: "Reply Hook", charLimit: 280 },
    ],
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    icon: LinkedinIcon,
    color: "#0A66C2",
    bgColor: "rgba(10, 102, 194, 0.1)",
    contentTypes: [
      { id: "post", label: "Post", charLimit: 3000 },
      { id: "carousel-script", label: "Carousel Script" },
      { id: "connection-note", label: "Connection Note", charLimit: 300 },
    ],
  },
  {
    id: "youtube",
    name: "YouTube",
    icon: YoutubeIcon,
    color: "#FF0000",
    bgColor: "rgba(255, 0, 0, 0.1)",
    contentTypes: [
      { id: "video-title", label: "Video Title", charLimit: 100 },
      { id: "description", label: "Description", charLimit: 5000 },
      { id: "shorts-hook", label: "Shorts Hook", charLimit: 100 },
      { id: "community-post", label: "Community Post", charLimit: 2000 },
    ],
  },
];

// Tones
export const TONES: { id: Tone; label: string; emoji: string; description: string }[] = [
  { id: "professional", label: "Professional", emoji: "💼", description: "Polished & authoritative" },
  { id: "casual", label: "Casual", emoji: "😎", description: "Friendly & conversational" },
  { id: "humorous", label: "Humorous", emoji: "😂", description: "Witty & engaging" },
  { id: "inspirational", label: "Inspirational", emoji: "✨", description: "Motivating & uplifting" },
  { id: "storytelling", label: "Storytelling", emoji: "📖", description: "Narrative & immersive" },
];

// Languages
export const LANGUAGES: { id: Language; label: string; flag: string }[] = [
  { id: "english", label: "English", flag: "🇺🇸" },
  { id: "hindi", label: "Hindi", flag: "🇮🇳" },
  { id: "hinglish", label: "Hinglish", flag: "🇮🇳🇺🇸" },
];

// Plan limits
export const PLAN_LIMITS = {
  free: {
    generationsPerMonth: 10,
    templates: false,
    customTemplates: false,
    allTones: false,
    priorityGeneration: false,
    allowedTones: ["professional", "casual", "inspirational"] as Tone[],
  },
  pro: {
    generationsPerMonth: 50,
    templates: true,
    customTemplates: false,
    allTones: true,
    priorityGeneration: true,
    allowedTones: ["professional", "casual", "humorous", "inspirational", "storytelling"] as Tone[],
  },
  business: {
    generationsPerMonth: Infinity,
    templates: true,
    customTemplates: true,
    allTones: true,
    priorityGeneration: true,
    allowedTones: ["professional", "casual", "humorous", "inspirational", "storytelling"] as Tone[],
  },
};

// 20 Pre-built Templates
export const DEFAULT_TEMPLATES = [
  {
    name: "Product Launch",
    description: "Announce a new product or feature launch",
    platform: "instagram" as Platform,
    contentType: "caption" as ContentType,
    tone: "professional" as Tone,
    language: "english" as Language,
    topic: "We're thrilled to announce the launch of [Product Name] — designed to [key benefit]. Available now!",
    icon: "🚀",
  },
  {
    name: "Motivational Quote",
    description: "Inspire your audience with a powerful quote",
    platform: "instagram" as Platform,
    contentType: "caption" as ContentType,
    tone: "inspirational" as Tone,
    language: "english" as Language,
    topic: "Write a motivational post about overcoming challenges and staying focused on your goals",
    icon: "💪",
  },
  {
    name: "Flash Sale",
    description: "Create urgency with a limited-time offer",
    platform: "instagram" as Platform,
    contentType: "caption" as ContentType,
    tone: "casual" as Tone,
    language: "english" as Language,
    topic: "Flash sale — 50% off everything for the next 24 hours. Use code SAVE50.",
    icon: "🔥",
  },
  {
    name: "Behind the Scenes",
    description: "Show the human side of your brand",
    platform: "instagram" as Platform,
    contentType: "reel-hook" as ContentType,
    tone: "casual" as Tone,
    language: "english" as Language,
    topic: "A day in the life at [Company] — what really goes on behind closed doors",
    icon: "🎬",
  },
  {
    name: "Customer Testimonial",
    description: "Share a glowing customer review",
    platform: "linkedin" as Platform,
    contentType: "post" as ContentType,
    tone: "professional" as Tone,
    language: "english" as Language,
    topic: "One of our customers shared how [Product] helped them achieve [specific result]",
    icon: "⭐",
  },
  {
    name: "How-To Tutorial",
    description: "Teach your audience something valuable",
    platform: "youtube" as Platform,
    contentType: "description" as ContentType,
    tone: "professional" as Tone,
    language: "english" as Language,
    topic: "Step-by-step tutorial on how to [specific skill/task] for beginners",
    icon: "📚",
  },
  {
    name: "Industry News",
    description: "Comment on latest industry trends",
    platform: "twitter" as Platform,
    contentType: "thread" as ContentType,
    tone: "professional" as Tone,
    language: "english" as Language,
    topic: "Breaking down the latest trend in [industry] and what it means for professionals",
    icon: "📰",
  },
  {
    name: "Team Introduction",
    description: "Introduce team members to your audience",
    platform: "linkedin" as Platform,
    contentType: "post" as ContentType,
    tone: "casual" as Tone,
    language: "english" as Language,
    topic: "Meet [Name], our [Role]. They bring [years] of experience in [field]",
    icon: "👥",
  },
  {
    name: "Event Promotion",
    description: "Promote an upcoming event or webinar",
    platform: "linkedin" as Platform,
    contentType: "post" as ContentType,
    tone: "professional" as Tone,
    language: "english" as Language,
    topic: "Join us for [Event Name] on [Date]. Learn about [topics] from industry experts.",
    icon: "🎉",
  },
  {
    name: "Thought Leadership",
    description: "Share your unique perspective on industry topics",
    platform: "linkedin" as Platform,
    contentType: "post" as ContentType,
    tone: "professional" as Tone,
    language: "english" as Language,
    topic: "My controversial take on [industry topic] that most people get wrong",
    icon: "🧠",
  },
  {
    name: "Personal Story",
    description: "Connect through authentic personal experience",
    platform: "instagram" as Platform,
    contentType: "caption" as ContentType,
    tone: "storytelling" as Tone,
    language: "english" as Language,
    topic: "The story of how I went from [starting point] to [achievement] in [timeframe]",
    icon: "📝",
  },
  {
    name: "Tips & Tricks",
    description: "Share actionable tips your audience can use",
    platform: "twitter" as Platform,
    contentType: "thread" as ContentType,
    tone: "casual" as Tone,
    language: "english" as Language,
    topic: "10 tips for [topic] that will save you hours every week",
    icon: "💡",
  },
  {
    name: "Q&A Session",
    description: "Engage your community with a Q&A prompt",
    platform: "youtube" as Platform,
    contentType: "community-post" as ContentType,
    tone: "casual" as Tone,
    language: "english" as Language,
    topic: "Ask me anything about [topic]. Drop your questions below!",
    icon: "❓",
  },
  {
    name: "Milestone Celebration",
    description: "Celebrate your brand or personal achievement",
    platform: "instagram" as Platform,
    contentType: "caption" as ContentType,
    tone: "inspirational" as Tone,
    language: "english" as Language,
    topic: "We just hit [milestone] and we couldn't have done it without you!",
    icon: "🎯",
  },
  {
    name: "UGC Prompt",
    description: "Encourage user-generated content",
    platform: "instagram" as Platform,
    contentType: "caption" as ContentType,
    tone: "casual" as Tone,
    language: "english" as Language,
    topic: "Share your [product/experience] photos with #[hashtag] for a chance to be featured!",
    icon: "📸",
  },
  {
    name: "Trend Commentary",
    description: "Jump on a trending topic with your take",
    platform: "twitter" as Platform,
    contentType: "tweet" as ContentType,
    tone: "humorous" as Tone,
    language: "english" as Language,
    topic: "Hot take on the latest [trending topic] that everyone is talking about",
    icon: "📈",
  },
  {
    name: "Before & After",
    description: "Showcase transformation results",
    platform: "instagram" as Platform,
    contentType: "reel-hook" as ContentType,
    tone: "casual" as Tone,
    language: "english" as Language,
    topic: "Watch this incredible transformation from [before state] to [after state]",
    icon: "🔄",
  },
  {
    name: "Day in the Life",
    description: "Share a relatable daily routine",
    platform: "youtube" as Platform,
    contentType: "shorts-hook" as ContentType,
    tone: "casual" as Tone,
    language: "english" as Language,
    topic: "A productive day in the life of a [profession/role]",
    icon: "☀️",
  },
  {
    name: "Bold Opinion",
    description: "Share a thought-provoking perspective",
    platform: "twitter" as Platform,
    contentType: "tweet" as ContentType,
    tone: "professional" as Tone,
    language: "english" as Language,
    topic: "Unpopular opinion: [controversial but insightful take on industry topic]",
    icon: "🔥",
  },
  {
    name: "Educational Thread",
    description: "Break down a complex topic into digestible parts",
    platform: "twitter" as Platform,
    contentType: "thread" as ContentType,
    tone: "professional" as Tone,
    language: "english" as Language,
    topic: "Everything you need to know about [topic] explained simply — a comprehensive guide",
    icon: "🎓",
  },
];
